# `Tensors`

In [ ]:
import numpy as np
import torch

## **NumPy** `Array`

In [ ]:
array = np.zeros((3,100))
print(array.dtype)

float64


## **PyTorch** `tensor`

In [ ]:
tensor1 = torch.zeros((3,100))
print(tensor1.dtype)

torch.float32


## `tensor` **operations**

In [ ]:
tensor2 = torch.tensor(array)
print(tensor2.dtype)

torch.float64


In [ ]:
tensor3 = tensor2.reshape(2, -1)
tensor3.shape

torch.Size([2, 150])

In [ ]:
tensor3[0][0] = 1
tensor2[0]

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)

## `tensor` **math**

In [ ]:
torch.sub(tensor1 + tensor2, tensor1 - tensor2)

tensor([[2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         

In [ ]:
torch.tensor(np.array([i for i in range(150)])) ** torch.arange(150)

tensor([                   1,                    1,                    4,
                          27,                  256,                 3125,
                       46656,               823543,             16777216,
                   387420489,          10000000000,         285311670611,
               8916100448256,      302875106592253,    11112006825558016,
          437893890380859375,                    0, -2863221430593058543,
         -497033925936021504,  6353754964178307979, -2101438300051996672,
        -1595931050845505211,  4981753131911086080,  8450172506621111015,
                           0, -6776596920136667815, -1123307876295639040,
        -5278486589563110205, -6845471433603153920,  5529354540715494413,
         2565992168703393792, -4642015662142636065,                    0,
        -4053175462519618527, -5296008294479953920,  8407224849895527163,
                           0, -4689350456247753643,  6543552412563537920,
        -8795647696940200745,         